name: Assign Random Reviewer to Pull Requests

author: Adresta AG

description: This action assigns the pull request to a random reviewer out of a list of possible reviewers.

inputs:
  repo-token:
    description: The github token needed to grant this action access rights to the pull request.
    required: true
    default: ${{ github.token}}
  reviewers:
    description: A list of github users that can be assigned to this PR.
    required: true

runs:
  using: 'node12'
  main: 'main.js'
